### ISSUE TITLE
Integrate SBoMs to Open Component Model

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-spec#82]
**What would you like to be added**:
Standardized support for SbOMs in OCM

**Why is this needed**:
Motivation i in ADR:

# ADR: SBoM integration into OCM

This ADR proposes introducing a new artifact type "sbom" to standardize accessing and storing bill of materials as part of the open-component-model. SBoMs become an important part of build and delivery processes. The Open Component Model should provide a standardized way to integrate SBoMs.

* Status: proposed   
* Date: 2023-08-23 
* Authors: OCM Maintainers
* Deciders:  
* Version: 0.0.1

## Context

Securing the software supply chain becomes a more and more important aspect for secure software deliveries. Multiple official guidelines from governmental departments have been published or are proposed, e.g. by German BSI [^1], European Commission [^2] or the U.S White House[^3]. Often a software bill-of-materials (SBoM) is enforced in this context to be included in a software delivery.

The Open-Component-Model is not the same as an SBoM. Its focus is on the delivery aspect and the delivered artifacts needed for a software deployment (e.g. Container Images, Helm Charts, etc.) Given the increasing importance of SBoMs it makes sense to make the SBoM part of an OCM component version and include it in the OCM component descriptor.

The proposed way to include the SBoM to the Open Component Model is to:

 * rely on existing standard formats for describing SBoMs like Cyclon DX[^4] or SPDX [^5]
 * Store the SBoM as an additional `resource` of a component version
 * Define a new (global) artifact type `sbom` to indicate that the resource is a bill-of-material
 * Define a relationship between an sbom resource and another resource (often a container image) to indicate the artifact described by the sbom

Storing an sbom is already possible with the exisiting OCM specification (version 0.1.0)

* An SBoM can be added as a `file` resource
* The technical format can be set in the `mediaType` attribute of a file artifact
* The relationship can be descibed using `labels`.

Example:

```
apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/jensh007/microblog
  provider:
    name: ocm.software
  version: 0.23.1
repositoryContexts: ...
spec:
  resources:
  - access:
      localReference: sha256:07a03193fd7db64e5c15ef83327ef22ad3ca6e19fa524033f4e4e196e18699db
      mediaType: application/vnd.oci.image.manifest.v1+tar+gzip
      referenceName: ghcr.io/jensh007/microblog/charts/microblog:0.23.1
      type: localBlob
    name: microblog-chart
    relation: local
    type: helmChart
    version: 0.23.1
  - access:
      imageReference: ghcr.io/jensh007/microblog/images/microblog:0.23.1
      type: file
    name: microblog-image
    relation: external
    type: ociImage
    version: 0.23.1
  - access:
      localReference: sha256:49d90dc226bdee95a69bc38ea914d524a8cd4ca189a01afc7e33ac46ff91ff9d
      mediaType: application/spdx+json
      type: localBlob
    labels:
    - name: owner
      value:
        ref: microblog-image
    name: microblog-sbom
    relation: local
    type: filesystem
    version: 0.23.1
  sources: ...
```

This approach has however some disadvantages:

* A file is a very generic resource type. A consumer of a component descriptor has no information that this file resource is an sbom
* Labels are a generic mechaninsm to supply any kind of information. Defining the relationship between SBOM and SBoM target artifact should be made explicit.

# Proposal

The proposal is to add a new global artifact type `sbom`. Otherwise the semantics is the same as for the `filesystem` artifact type. During creation of the component version it is the task of the creator to provide the SBoM file as input.

The reference between the SBoM and the resource it describes uses an artifact reference (see [OCM spec](https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#artifact-references))

There are several ways to model the reference between the sbom and the decribed reosurce:

* provide an additional attribute `refers-to` or similar to access type localBlob (see appendix B)
* provide a standardized label (similar to the example above, potentially with enriched information)
* The relationship can be stored in the sbom resource ("describes") or at the resource referring to the sbox ("described-by")

Multiple sbom resources within a component version are possible. However for each resource there must be at most one sbom referring to it (1:1 relationship).

### Possible Enhancements

* Store the SBOM (optional) as a separate OCI Artifact (comparable to a helm chart). This makes access easier available for non OCM-aware tools

## Decision
*to be done*

## Consequences
Following this ADR it is possible for OCM aware tools to access SBoMs in a defined and standardized manner. With the help of OCM it is possible for build and delivery infrastructures to simplify the fulfillment of official regulations for software supply chain security.

# Appendix

[^1]: [Technische Richtlinie TR-03183](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03183/BSI-TR-03183-2.pdf?__blob=publicationFile&v=3)

[^2]: [EU Cyber Resilience Act](https://digital-strategy.ec.europa.eu/en/library/cyber-resilience-act)

[^3]: [U.S Executive Order 14028 ](https://www.gsa.gov/technology/it-contract-vehicles-and-purchasing-programs/technology-products-services/it-security/executive-order-14028/)

[^4]: [CycloneDX](https://cyclonedx.org/specification/overview/)

[^5]: [Software Package Data eXchange (SPDX)](https://spdx.dev/specifications/)
